"""init schema

Revision ID: 090aa48f8c7b
Revises: 
Create Date: 2026-03-03 10:38:27.729810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090aa48f8c7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=100), nullable=False),
    sa.Column('numero_permis', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_client'),
    sa.UniqueConstraint('numero_permis')
    )
    op.create_table('utilisateur',
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.Column('identifiant', sa.String(length=50), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_utilisateur'),
    sa.UniqueConstraint('identifiant')
    )
    op.create_table('vehicule',
    sa.Column('id_vehicule', sa.Integer(), nullable=False),
    sa.Column('marque', sa.String(length=50), nullable=False),
    sa.Column('modele', sa.String(length=50), nullable=False),
    sa.Column('immatriculation', sa.String(length=20), nullable=False),
    sa.Column('prix_par_jour', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('statut', sa.String(length=20), server_default='disponible', nullable=False),
    sa.CheckConstraint("statut IN ('disponible', 'loue')", name='chk_vehicule_statut'),
    sa.CheckConstraint('prix_par_jour > 0', name='chk_vehicule_prix_positif'),
    sa.PrimaryKeyConstraint('id_vehicule'),
    sa.UniqueConstraint('immatriculation')
    )
    op.create_table('location',
    sa.Column('id_location', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('prix_total', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('statut', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('id_vehicule', sa.Integer(), nullable=False),
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.CheckConstraint("statut IN ('active', 'terminee')", name='chk_location_statut'),
    sa.CheckConstraint('date_fin >= date_debut', name='chk_location_dates'),
    sa.CheckConstraint('prix_total >= 0', name='chk_location_prix_total'),
    sa.ForeignKeyConstraint(['id_client'], ['client.id_client'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id_utilisateur'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_vehicule'], ['vehicule.id_vehicule'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_location')
    )
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.create_index('idx_location_client', ['id_client'], unique=False)
        batch_op.create_index('idx_location_dates', ['date_debut', 'date_fin'], unique=False)
        batch_op.create_index('idx_location_vehicule', ['id_vehicule'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_index('idx_location_vehicule')
        batch_op.drop_index('idx_location_dates')
        batch_op.drop_index('idx_location_client')

    op.drop_table('location')
    op.drop_table('vehicule')
    op.drop_table('utilisateur')
    op.drop_table('client')
    # ### end Alembic commands ###
